function BulkTab() {
    return (
        <>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Previous Token Id' />
            </div>
            <div className='box-container'>
                <input className='' type='checkbox'/>
                <label for="scales"> I am minting more on a tokenID already created</label>
            </div>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Token Name'/>
            </div>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Token Symbol' />
            </div>
            <div className='box-container'>
                <input className='text-input' type='number' placeholder='Max Supply' />
            </div>
            <div className='box-container'>
                <input className='text-input' type='number' placeholder='Number of Royalty Accounts' />
            </div>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Treasury Account ID' />
            </div>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Auto Renew Account ID' />
            </div>
            <div className='box-container'>
                <input className='text-input' type='text' placeholder='Fallback Fee' />
            </div>
            <div className='box-container'>
                <input className='' type='checkbox'/>
                <label > Add a ADMIN Key</label>
            </div>
            <div className='box-container'>
                <input className='' type='checkbox'/>
                <label > Add a FREEZE Key</label>
            </div>
            <div className='box-container'>
                <label > Select the directory that has all of your hashlips images generated by Hashlips:</label>
            </div>
            <div className='box-container'>
                <input type='file' />
            </div>
            <div className='box-container'>
                <label > Select the _metadata.json file that has all of your file metadata generated by Hashlips:</label>
            </div>
            <div className='box-container'>
                <input type='file' />
            </div>
            <div className='box-container'>
                <input className='' type='checkbox'/>
                <label for="scales"> I am minting more on a tokenID already created</label>
            </div>
            <div className='box-container'>
                <button className="flip-button" tabIndex="0" style={{width:"100%"}}>
                    MINT COLLECTION
                </button>
            </div>
        </>
    );
  }
  
  export default BulkTab;
  